# Generated by Django 4.2.20 on 2025-05-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comments_contact2'),
        ('myapp', '0002_order'),
    ]

    operations = [
    ]
