# Generated by Django 5.1.6 on 2025-05-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_0002_comments_contact2_0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Name',
            new_name='name',
        ),
    ]
